# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b3935063b2dbb5f8bc88398415babf1a3d259c80a1c3349fc69aacf7e8acd50de11408491086dc14a1e2b4f86889910136f0492d91a037339d0d62cac6152e6

test:
  secret_key_base: 804117e6be5ba4fbaa8d2e2e970a64fafc99a66044a1c172fcb4df630b09c68c7c313fad9e0bcad9e4724c821f2d8c6b759455fea125b7df559c99eb4ede8c9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
